// examples/vue2-example/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <div class="data">
      <div class="bbcode">
        <h2>Raw BB Code here</h2>
        <textarea name="bbcode" id="bbcode" cols="30" rows="10" v-model="bbcode"></textarea>
      </div>
      <div class="html">
        <h2>Generated HTML here</h2>
        <bbob-bbcode container="div" :plugins="plugins">{{ bbcode }}</bbob-bbcode>
      </div>
    </div>
    <pre class="code"></pre>

  </div>
</template>

<script>
import Vue from 'vue'
import preset from '@lng2004/bbob-preset-vue'
import MyTag from './MyTagComponent'

const myPreset = preset.extend(defTags => ({
  ...defTags,
  // bbcode tags always lowercased
  mytag: (node) => ({
    ...node,
    tag: MyTag,
  })
}))

export default Vue.extend({
  name: 'App',
  data() {
    return {
      bbcode: 'Text [b]bolded[/b] and [myTag]Some Name[/myTag]',
      plugins: [
        myPreset()
      ],
    }
  }
})
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;

  width: 700px;
  margin: 60px auto 0;
}

.data {
  display: flex;
  justify-content: space-between;
}

.bbcode,
.html {
  border: 1px solid #ccc;
  width: 300px;
}
</style>

// examples/react-vite/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

import preset from '@lng2004/bbob-preset-react'
import BBCode from '@lng2004/bbob-react'
import Avatar from "./components/Avatar";

const myPreset = preset.extend(defTags => ({
  ...defTags,
  // bbcode tags always lowercased
  avatar: (node) => ({
    ...node,
    tag: Avatar,
  })
}))

const plugins = [
  myPreset()
]

function App() {
  const [bbcode, setBBCode] = useState('Text [b]bolded[/b] and [avatar]Some Name[/avatar]')

  const onInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setBBCode(e.target.value)
  }

  return (
      <>
        <div>
          <a href="https://vitejs.dev" target="_blank">
            <img src={viteLogo} className="logo" alt="Vite logo"/>
          </a>
          <a href="https://react.dev" target="_blank">
            <img src={reactLogo} className="logo react" alt="React logo"/>
          </a>
        </div>
        <div className="data">
          <div className="bbcode">
            <h2>Raw BB Code here</h2>
            <textarea name="bbcode" id="bbcode" cols={30} rows={10} onInput={onInput} defaultValue={bbcode} />
          </div>
          <div className="html">
            <h2>Generated HTML here</h2>
            <BBCode plugins={plugins}>{bbcode}</BBCode>
          </div>
        </div>
      </>
  )
}

export default App
